name: Build on main push

on:
  push:
    branches:
      - main

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build fulcrum image
    runs-on: ubuntu-latest
    env:
      VERSION: v1.8.2
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      # Setup environment
      - name: Set WORKER_COUNT env
        run: echo "WORKER_COUNT=$(nproc)" >> $GITHUB_ENV

      - name: Login to docker hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Create buildx worker node
        run: docker buildx create --use

      - name: Show available Docker buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Docker buildx
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --build-arg MAKEFLAGS="-j ${WORKER_COUNT}" \
          --build-arg VERSION=$VERSION \
          --tag ${{ secrets.DOCKER_HUB_USER }}/fulcrum:$VERSION \
          --output "type=registry" .
